language: objective-c
osx_image: xcode9.3
xcode_workspace: LinkedinSwift/LinkedinSwift.xcworkspace/
xcode_scheme: LinkedinSwift
xcode_sdk: iphonesimulator
podfile: LinkedinSwift/Podfile
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace LinkedinSwift/LinkedinSwift.xcworkspace -scheme LinkedinSwiftTests CODE_SIGNING_REQUIRED=NO